# ===== Encoder =====
encoder_ckpt_path: checkpoints/encoder.pt

# ===== Decoder (DiT) =====
decoder_ckpt_path: checkpoints/runs/flow_tse_stft_m2s_crossattnv2_bs4_epoch5.pt
dim: 256
depth: 8
n_head: 8
dim_head: 64
ff_mult: 4
dropout: 0.1
long_skip_connection: true
cond_drop_prob: 0.1

# ===== Data =====
n_fft: 512
hop_length: 128
win_length: 512
sample_rate: 16000
snr_db_range: [0, 10]
source_num: 3
min_source_num: 3
active_num: [-1, 1]
batch_size: 4

# ===== Training =====
epochs: 10
steps_per_epoch: 500
grad_clip: 1.0
lr: 1.0e-4
